### ISSUE TITLE
ETH Balance wrong for Rocketpool Share

### ISSUE THREAD

**Issue by Dresel** [gobitfly/eth2-beaconchain-explorer-app#104]
**Describe the bug**
If you set an ETH share for a rocketpool validator, the balance is calculated wrong.

**To Reproduce**
1. Add Rocketpool Validator
2. Set ETH Share to 8 ETH (will be correctly shown as 50% in the overview)
3. Check balance in detail view, it will be < 8 ETH

**Expected behavior**
Balance should be calculated correctly.

**Phone (please complete the following information):**
 - iOS & Android 
 - App Version 3.2.3

**Comment by manuelsc** [comment]
Thanks for the bug report. This is fixed in 3.3.0 which is currently slowly being rolled out on the stores, should be available in the next couple days.
