### ISSUE TITLE
changing the "rocketpool max collateral" setting is not saved

### ISSUE THREAD

**Issue by lfinbob** [gobitfly/eth2-beaconchain-explorer-app#107]
Going to Settings => Notifications => Rocketpool Node and changing any of the 4 collateral settings never has any effect.
Leaving the settings view and coming back to it the previous values are back.

**To Reproduce**
1. Go to Settings => Notifications => Rocketpool Node and change the "max collateral" toggle (from on to off in my case)
2. Leave the Notifications screen
3. Go back to the Notifications screen. The "max collateral" toggle is on again

**Versions**
- Google Pixel with stock Android 12, latest updates
- App Version 3.2.3 (latest on Play Store)

**Comment by lfinbob** [comment]
I can reproduce this on another clean app install with only adding one validator (#244323).
Another user in the rocketpool discord confirmed the bug, but only after upgrading to the latest beaconchain app on iOS. It's not known which version they had before.

**Comment by manuelsc** [comment]
Thanks for the bug report. Notifications may not be synced immediately, it might take a couple seconds before the changes apply. We improved this in the latest release 3.3.0 which is currently available on the play store and slowly rolling out on the app store. If you wait 2-3 seconds before entering the notifications screen again the state of the toggle should now be correct to where you set it.

**Comment by lfinbob** [comment]
Unfortunately not the case. I've now waited 30 Seconds at every screen, no change. I'm trying to change this settings since a few days and can't manage to do it any way.

**Comment by lfinbob** [comment]
I've updated to the latest 3.3.1 from PlayStore and the problem still persists. Even if I wait 60 seconds after changing a setting. Still not saved. Can reproduce on a fresh device with a clean install.

**Comment by manuelsc** [comment]
I think I found the culprit. As a workaround you can try to press the back arrow on the notification screen at the top, not your android hardware button to navigate back. Or changing the setting, closing the app and opening again should trigger the sync.

**Comment by lfinbob** [comment]
Really sorry to disappoint, but both workarounds don't help. On my main device and my fresh-install repro-device. Both Android 12 with BeaconChain app 3.3.1.
Here's a repro pic:
![bc-repro](https://user-images.githubusercontent.com/99162861/182641772-632985fb-4885-4f6a-b2a6-a0d6c14a8e9b.png)

**Comment by lfinbob** [comment]
Note that in the repro I waited 10 seconds between every step, as you mentioned it could take a while to apply

**Comment by manuelsc** [comment]
Can you maybe provide me with some logs so I can get to the bottom of this. After trying to change the setting, press the version number three times at the bottom of the apps setting screen. And mail me the logs at manuel@bitfly.at - don't post them here since they could contain sensible information.

**Comment by lfinbob** [comment]
Unfortunately the "copy to clipboard" log feature is broken. It gives the "copied to clipboard" toast notification, but the clipboard still contains the content of whatever it contained before.
So all I can do is give you screenshots, but that would be like 50+ hard-to read and unsearchable pictures.
How can we proceed? Can you fix the log copy feature first? 
Repro fog log-copy-bug:

1. Tap version 3 times
2. Select "current session"
3. (optional) press expand button
4. Press copy button
5. Toast notification "copied to clipboard" appears, but clipboard contains old content

**Comment by lfinbob** [comment]
Just checked: Upgrading to 3.4.2 doesn't fix either issue.

**Comment by manuelsc** [comment]
Can you mail me your beaconcha.in account E-Mail? And one last thing that came to my mind that my help, could you go to the validators list, press the sync button, then try changing the setting again?

**Comment by lfinbob** [comment]
Send my repro-beaconcha.in account by mail!
Syncing the validator list did not help.
Thanks for getting to the bottom of this issue.

**Comment by manuelsc** [comment]
Thanks for all your help. I found the issue and will test the fix for the next couple days on the testnets before we will deploy it on mainnet next week. To speed things up, I fixed it for your account in the mean time manually, your toggle should now be off.

**Comment by lfinbob** [comment]
Can you say when this fixed will be released? I'm getting annoying notifications every day as long as I'm unable to change the setting. Thank you in advance.
