### ISSUE TITLE
Beaconchain app shows NaN

### ISSUE THREAD

**Issue by jerryji** [gobitfly/eth2-beaconchain-explorer-app#111]
**Describe the bug**
My Beaconchain app starts to show NaN values since yesterday

**To Reproduce**
Just open the app

**Expected behavior**
Show correct values

**Screenshots**
![NaN](https://user-images.githubusercontent.com/83122/182603448-a8647e00-2fe5-4adb-8de2-07d49ac77551.jpg)

**Phone (please complete the following information):**
 - OS: Android 12 (One UI 4.1)
 - App Version 3.4.0

**Additional context**
* Values shown on beaconcha.in website are correct
* Started since yesterday (02-Aug-2022)
* No OS / app upgrade since yesterday

**Comment by manuelsc** [comment]
Can you provide us with logs. Click three times on the app version on the apps setting page down at the bottom. Don't post them here since they could contain sensible information, send them to manuel@bitfly.at.

**Comment by jerryji** [comment]
The weird thing is the Copy icon on top of Logview does _not_ copy anything to my clipboard even though the message "Copied to clipboard" pops up so I couldn't figure out any way to save and transfer the entire log.

That said, there seems be only one WARN message in the entire log and hopefully that's the culprit --

![Screenshot_20220804-102317_Beaconchain](https://user-images.githubusercontent.com/83122/182749580-55ad72f2-deb0-4bf1-89a7-aaf2b4d29e6b.jpg)

**Comment by ph1go** [comment]
I have this issue too (Android) and I also can't get the logs to copy. 

I can see that the call to `https://beaconcha.in/api/v1/app/dashboard` returns good data (ie I can see the validator balances) and the next log entry "dashboard data" is where the NaNs appear for the performance1/7/365d attributes.

**Comment by manuelsc** [comment]
We published a new version 3.4.2 on the play store. Could you please try and get back to me whether this fixes the issue?

**Comment by lfinbob** [comment]
It does fix the issue for me. Thanks Manuel!
The log copy bug which the others described is still in 3.4.2.
