### ISSUE TITLE
iPhone App Showing Two Nodes’ Metrics

### ISSUE THREAD

**Issue by nate-walter** [gobitfly/eth2-beaconchain-explorer-app#112]

**Comment by nate-walter** [comment]
In rocketpool service config  > Monitoring / Metrics Settings, I named my Nuc a generic name, Smartnode and saved. I then went back and renamed it to something else and saved. Now both Nodes show up in the mobile app and I can’t delete the first Node, Smartnode

**Comment by manuelsc** [comment]
The first one should automatically dissapear after a couple of hours

**Comment by nate-walter** [comment]
@manuelsc It did, thanks. Anything you want me to do on my end now? I'm new to GitHub Issues

**Comment by manuelsc** [comment]
All good, I'll close the issue :)
