### ISSUE TITLE
Log copy feature not working (doesn't copy anything)

### ISSUE THREAD

**Issue by lfinbob** [gobitfly/eth2-beaconchain-explorer-app#113]
Repro for log-copy-bug:

* Tap version 3 times
* Select "current session"
* (optional) press expand button
* Press copy button

Upon pasting there are no logs, but whatever content the clipboard contained previously.

**Expected behavior**
Pasting anywhere pastes the logs

 - OS: Android 12
 - App Version 3.4.2

**Comment by manuelsc** [comment]
thank you for bringing this to our attention, we fixed this in the latest release.
