### ISSUE TITLE
After updating to version 3.4.0 on iOS, earned Ether show NaN in red

### ISSUE THREAD

**Issue by brddd** [gobitfly/eth2-beaconchain-explorer-app#114]
After updating to version 3.4.0 from the iOS App Store, I no longer can see earned Ether.   All other stats and functionality seems ok.
![IMG_1098](https://user-images.githubusercontent.com/20145206/182941715-c30b4c02-8a8c-4e05-8abe-78050a8b25c0.jpg)

**Comment by yuilleb** [comment]
Same for Android.

**Comment by Buttaa** [comment]
@brddd @yuilleb please update to the latest version, this should be fixed now

**Comment by yuilleb** [comment]
Confirmed, it's fixed. Thanks!

**Comment by brddd** [comment]
Ditto.   All good on v3.4.2 on iOS.   Thanks!
