### ISSUE TITLE
Rocketpool Validator waiting on matching deposit brings down average effectiveness %

### ISSUE THREAD

**Issue by Woogz-git** [gobitfly/eth2-beaconchain-explorer-app#115]
If you have a RP Validator waiting on its matching deposit from the deposit pool its effectiveness will show as -1% which will mess up your average effectiveness if you have multiple validators.

Minor issue but would be better to just exclude it until it's active.

**Comment by manuelsc** [comment]
Thank you for bringing this to our attention, we fixed this in the latest release.
