### ISSUE TITLE
"Effectiveness" is calculated from what length of time?

### ISSUE THREAD

**Issue by JamesCropcho** [gobitfly/eth2-beaconchain-explorer-app#116]
On the app's Dashboard is a percentage metric called Effectiveness.

From what length of time is it calculated? (For example: "from the past 10 minutes," "from the past hour," etc.)

Thank You,
James

**Comment by JamesCropcho** [comment]
Hey all, bringing this up one last time in case it got lost through the cracks.

Or, is this the incorrect venue for the question?

**Comment by Buttaa** [comment]
Closing (duplicate)

**Comment by mohammadfarari1360** [comment]
Hi good thanks
