### ISSUE TITLE
Rocketpool RPL reward calculation wrong since Redstone

### ISSUE THREAD

**Issue by torfbolt** [gobitfly/eth2-beaconchain-explorer-app#119]
**Describe the bug**
Since the Redstone update, the RPL next claim estimation is broken and shows very different results than the official rocketpool CLI client.

**Phone (please complete the following information):**
 - OS: Android
 - App Version 3.4.2

**Comment by manuelsc** [comment]
Should be fixed now

**Comment by manuelsc** [comment]
Should be fixed now
