### ISSUE TITLE
iOS widget not loading

### ISSUE THREAD

**Issue by dendofuman** [gobitfly/eth2-beaconchain-explorer-app#121]
**Describe the bug**
iOS widget does not show any validator data despite premium membership.  The rest of the iOS app works as expected, including other premium features (no adds, customizable alerts, etc.). 

**To Reproduce**
1. Install iOS app from App Store
2. Run app and log into Beaconcha.in account
3. Reset app to load premium features. 
4. Add Beaconcha.in widget to Home Screen using procedure described in widget section of app settings. 
5.  Long press widget and select metrics to display, currency.  Set Rocketpool metrics to “no”6. 
6.  Observe that data is blank on widget screw 

**Expected behavior**
Validator metrics are shown on iOS widget 

**Screenshots**
![56433FA3-E05F-4A03-A921-90585DEEC542](https://user-images.githubusercontent.com/108909770/189928104-fba95616-a8e2-4523-b05b-204006bb122c.jpeg)
![5B069A46-4D94-4687-AFB7-7C479BA4CAC0](https://user-images.githubusercontent.com/108909770/189928112-a1177fb9-88ed-4773-a52b-acf314db8d11.jpeg)

**Phone (please complete the following information):**
 - OS: iOS 15.6.1
 - App Version 3.4.2

**Additional context**
I have tried remove and re-adding both the widget and the app multiple times, as well as logging out and re-logging into my account on the app.

**Comment by manuelsc** [comment]
Please update to 3.4.3 which fixes this
