### ISSUE TITLE
On iOS 16 the upgrade to premium is not recognized by the app

### ISSUE THREAD

**Issue by chmllr** [gobitfly/eth2-beaconchain-explorer-app#124]
IPhone 13, iOS 16 

Upgraded to Plankton plan, but the ads are still displayed.  When I try to restore the purchase it says it’s successful, restarts the app, but the ads are still there and I see no changes to the free plan.

Please let me know if more information is needed.

**Comment by chmllr** [comment]
Update: canceling the Apple subscription and subscribing via beaconcha.in directly, then logging again in the app solved the issue.

**Comment by Vitiell0** [comment]
Running into the same problem - upgrading to the premium version does not work on iOS 16

**Comment by manuelsc** [comment]
Thank you for bringing this to our attention. We found the problem and deployed a fix on our servers. Sorry for the inconvenience caused and thank you for your support!

**Comment by matkam** [comment]
@manuelsc seems like this issue is back. I still see ads after subscribing in iOS 17
