### ISSUE TITLE
CPU Charts broken for Lighthouse Beacon

### ISSUE THREAD

**Issue by mrpez1** [gobitfly/eth2-beaconchain-explorer-app#128]
IOS 15.7/16, iphone 12, Ipad Air 2022

For the last couple of days, CPU charts have been unreadable due to extreme/spurious readings on the left drowning out actual data to the right. This appears to affect lighthouse beacon (on multiple staking machines) but not Teku or machines with lighthouse validator only. Different time ranges show the spurious data in different time slots or not at all. 24 hour chart data is about double the correct reading (~20%):

![IMG_1](https://user-images.githubusercontent.com/112206437/192317531-f4d2ee14-e48d-4045-8170-052773599cf5.jpg)
![IMG_2](https://user-images.githubusercontent.com/112206437/192317554-d6fe7879-3812-4f0e-ab9f-5b95de665c28.jpg)
![IMG_3](https://user-images.githubusercontent.com/112206437/192317580-f3d326fb-495c-436f-b173-b06b186ba6d7.jpg)

**Comment by manuelsc** [comment]
Sorry for the inconvenience we had some issues with our servers. Reporting should be back to normal now.
