### ISSUE TITLE
Feature request - attestation notifications 

### ISSUE THREAD

**Issue by Njoiyt** [gobitfly/eth2-beaconchain-explorer-app#129]
Please create more options for notifications.

If miss x attestations in a row = notify // this tells you something is down and needs attention 

If miss x attestations in x time = notify // this tells you, there is something bad is happening and needs attention.

X should be inputted by user.

With attestation missing becoming unavoidable and more frequent lately, I am tired of receiving notifications I can't fix.

**Comment by Novop** [comment]
+1 
Receiving the random missed attestation notification is not very helpful anymore. It is actually quite common, and quite distracting to receive such a notification so often.

Please consider implementing the 'x missed attestations in a row'

**Comment by Njoiyt** [comment]
Looks like something similar was implemented. Closing ticket.
