### ISSUE TITLE
Adding validators to dash does not stick after pasting node address in Beaconchain iOS app

### ISSUE THREAD

**Issue by BawBawBawBaw** [gobitfly/eth2-beaconchain-explorer-app#131]
**Describe the bug**
Described in title. Only some validators bookmark to dash, some validators don’t. 

**To Reproduce**
1. Go to Validators tab in bottom bar
2. Paste node address in search bar
3. Bookmark all validators
4. See error when going to dashboard. Not all validators that were bookmarked are visible in dash.

**Expected behavior**
All validators that were bookmarked to be visible in dash 

**Screenshots**
None

**Phone (please complete the following information):**
iOS

**Additional context**
None

**Comment by manuelsc** [comment]
Fixed in 4.0.2
