### ISSUE TITLE
Setting changes not saving

### ISSUE THREAD

**Issue by Woogz-git** [gobitfly/eth2-beaconchain-explorer-app#132]
Phone: OnePlus 8t
Android Version: 12
Beaconchain app version: 3.5.4

When trying to update my execution client to Geth from Besu and indicate my node is a Rocketpool node the changes don't save and immediately revert back when I leave the settings tab.

I've checked and confirmed I don't have an update available for the beaconchain app in the app store.

**Comment by manuelsc** [comment]
Fixed in 4.0.2
