### ISSUE TITLE
Beaconchain Max collateral bug

### ISSUE THREAD

**Issue by Woofah** [gobitfly/eth2-beaconchain-explorer-app#133]
**Describe the bug**

**To Reproduce**
1. This happens automatically every 8 hours or so. Even though I'm only at 32% collateral, it gives me notifications and emails every 8 hours stating I've reached 150% collateral.
2. Check validator #412295 and #287724 on beaconchain 
3. See attached
![Screenshot_20221015-061006_Chrome](https://user-images.githubusercontent.com/115876271/195986080-1e0b214a-78f4-46dc-9f26-1ab7c265801b.jpg)
![Screenshot_20221015-061144_Gmail](https://user-images.githubusercontent.com/115876271/195986320-9b35556c-d896-45ef-8c09-74396666a98e.jpg)
![Screenshot_20221015_061617](https://user-images.githubusercontent.com/115876271/195986323-4d17cf96-ebcd-410a-908a-d45b980ae999.jpg)
![Screenshot_20221015_061640](https://user-images.githubusercontent.com/115876271/195986338-5bd7c547-341b-4f16-8702-26c1ce004d5e.jpg)

**Expected behavior**
Should not be receiving these notifications.

**Screenshots**

**Phone (please complete the following information):**
 - OS: android v12 kernel 4.14.113
 - App Version beacon chain 3.5.4

**Additional context**

**Comment by manuelsc** [comment]
Please check your notification settings. You have set your max collateral alert to notify you if your collateral is smaller (<) a certain threshold. If you want to get notifications once you exceed a certain threshold make sure to set the slider to larger (>).
