### ISSUE TITLE
Beaconchain App Shows Validators Offline While They Are Not

### ISSUE THREAD

**Issue by jerryji** [gobitfly/eth2-beaconchain-explorer-app#141]
**Describe the bug**
Latest Beaconchain Android app incorrectly shows validators as Offline

**To Reproduce**
I'm not sure whether the same issue can be re-produced on your side, but it certainly persists with me even after I logout, uninstall, and reinstall Beaconchain app

**Expected behavior**
Should show validators Online (which beaconcha.in website does correctly)

**Screenshots**
![v](https://user-images.githubusercontent.com/83122/201702109-ed1e26d0-0e95-4313-ace7-a2c7dcaf3f72.jpg)

**Phone (please complete the following information):**
 - OS: Android 12
 - App Version 4.0.2

**Additional context**
Happened after I rebooted my staking server, which caused my validators to miss a few attestations for a few minutes

**Comment by manuelsc** [comment]
We are currently migrating some data on our servers. Please bear with us, it should resolve itself over the next couple hours. Sorry for the inconvenience caused.
