### ISSUE TITLE
Sync committee notifications not disappearing

### ISSUE THREAD

**Issue by torfbolt** [gobitfly/eth2-beaconchain-explorer-app#146]
**Describe the bug**
Both upcoming and active sync committee membership are displayed in a blue bar in the app. But even after the duties end, those notifications do not go away and they also cannot be removed manually. 

**To Reproduce**
1. Open app
2. Wait for sync committee duties 
3. See notification 
4. Sync duties end
5. Notifications still shown, even after app restart 

**Expected behavior**
The notifications can be manually removed or expire and disappear automatically. 

**Screenshots**

**Phone (please complete the following information):**
 - OS: Android

**Comment by manuelsc** [comment]
v4.0.3 released
