### ISSUE TITLE
Won’t let me sign in to my Validator 142

### ISSUE THREAD

**Issue by K0P01IL** [gobitfly/eth2-beaconchain-explorer-app#147]
**Describe the bug**
Beaconchain.in app isn’t letting me sign in to my validator. Says my email isn’t registered but I am still getting the emails for my validator and have paid for premium.

**To Reproduce**
1. Go to 'Beaconcha.in app or website'
2. Click on 'Sign in'
3. Put my information Sagpope1986@gmail.com
4. Error says email not found.
5. But when I got to register my email it says already exists.

**Expected behavior**
Should be able to sign in to my validator after all I have put in it.

**Screenshots**

**Phone (please complete the following information):**
 - OS: [16.1.1]
 - App Version []

**Additional context**
Ongoing issues please any help would be greatly appreciated.

**Comment by manuelsc** [comment]
Hi @K0P01IL please try again, we deployed a fix on our side that should fix it. Sorry for the inconvenience caused.

**Comment by K0P01IL** [comment]
Okay awesome thanks. I'll let you know if it worked.

**Comment by manuelsc** [comment]
Has this issue been resolved?

**Comment by K0P01IL** [comment]
Issue hasn’t been resolved.

**Comment by K0P01IL** [comment]
Also I know I haven’t been able to receive rewards or anything as well. Any info on this would also help.

**Comment by guybrush** [comment]
Please try to reset your password here: https://beaconcha.in/requestReset

**Comment by manuelsc** [comment]
Closed due to inactivity
