### ISSUE TITLE
Can only utilize four monitoring setups

### ISSUE THREAD

**Issue by mrpez1** [gobitfly/eth2-beaconchain-explorer-app#179]
Have "Whale" premium subscription which should allow 10 monitoring setups but can only monitor 4 servers. Used to be able to monitor more. Change appears to have happened in last week or two. Appears to be FIFO as first in servers will remain with stale data for a while and then eventually drop.

**Comment by manuelsc** [comment]
Hi, sorry for the delay. We've been a bit busy getting beaconcha.in and the app ready for Shapella.

Would you mind contacting us on discord or via support mail? https://discord.io/beaconchain 

I'd like to take a closer look at the issue on your account and may need to ask for the email and don't want you to have to disclose this publicly.
