### ISSUE TITLE
0x9FD5C62A90ED0508c11a724302A809CC16F42aEc

### ISSUE THREAD

**Issue by NASERALHADDAD** [gobitfly/eth2-beaconchain-explorer-app#210]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone (please complete the following information):**
 - OS: [e.g. iOS 14.5]
 - App Version [e.g. 22]

**Additional context**

**Comment by NASERALHADDAD** [comment]
0x047f052778729b86173f84302dfa1b6783be8c3e84ed58e6471076963f5ee47f

**Comment by Biqniq** [comment]
> 0x047f052778729b86173f84302dfa1b6783be8c3e84ed58e6471076963f5ee47f
