### ISSUE TITLE
Mobile app showing I proposed a block when I didn't

### ISSUE THREAD

**Issue by timjrobinson** [gobitfly/eth2-beaconchain-explorer-app#225]
**Describe the bug**
The latest block in my blocks list says it was proposed by my validator but when viewing the block details it was some other validator not owned by me

**Expected behavior**
I expect to only see blocks my validators submitted

**Screenshots**
![Screenshot_20230527-031303.png](https://github.com/gobitfly/eth2-beaconchain-explorer-app/assets/525534/c828983b-aa7c-42eb-9ab8-01eced5a5865)

522301 is my validator but it didn't propose that block

**Phone (please complete the following information):**
 - OS: Android 
 - App Version 4.2.4

**Additional context**

**Comment by timjrobinson** [comment]
Link to block: https://beaconcha.in/block/17296952

Can see that my validator didn't produce this block on there.

![Screenshot_20230527-031658.png](https://github.com/gobitfly/eth2-beaconchain-explorer-app/assets/525534/2cf86beb-db13-47b1-9c48-49db23b608f6)

**Comment by manuelsc** [comment]
Thank you for reporting this to us. We'll look into it.

**Comment by manuelsc** [comment]
Fixed with https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2258
