### ISSUE TITLE
Feature request: Allow choice of notification channel / stop emails

### ISSUE THREAD

**Issue by rambowtech** [gobitfly/eth2-beaconchain-explorer-app#229]
I receive push notifications and emails for all notifications. This is pretty redundant and annoying. Please allow me to deactivate emails.

**Comment by Buttaa** [comment]
> I receive push notifications and emails for all notifications. This is pretty redundant and annoying. Please allow me to deactivate emails.

hi @rambowtech you can already do that under notification channels, see: https://kb.beaconcha.in/beaconcha.in-explorer/beaconcha.in-notifications
