### ISSUE TITLE
Rewards chart doesnt show consensus rewards

### ISSUE THREAD

**Issue by Novop** [gobitfly/eth2-beaconchain-explorer-app#237]
![Screenshot_20230831_150103_Beaconchain](https://github.com/gobitfly/eth2-beaconchain-explorer-app/assets/13527777/dc19253c-612b-451d-b7bf-d515ef36071f)
**Describe the bug**
The rewards chart no longer shows Consensus rewards (blue). Only Execution rewards are shown. This happened 4-5 days ago.

**Phone (please complete the following information):**
 - OS: [android]
 - App Version [latest]

**Comment by adamgall** [comment]
I have the same issue on iOS.

**Comment by PerfectSense1** [comment]
Same problem here on iOS

**Comment by GHM1800** [comment]
Same for me on iOS. Annoying bug for quite some time now…

**Comment by manuelsc** [comment]
We are aware of the issue on iOS. A fix for Android is already live and we are currently waiting for Apples approval for the iOS fix.

**Comment by manuelsc** [comment]
Fixed with App version 4.3.3 - now available on the Appstore.
