### ISSUE TITLE
The “total” in the app dashboard does not match the actual amounts on beaconcha.in

### ISSUE THREAD

**Issue by man55** [gobitfly/eth2-beaconchain-explorer-app#251]
**Describe the bug**

The “total” in the app dashboard does not match the actual amounts on beaconcha.in

**To Reproduce**
View the “total” in the application and on the website. Compare numbers.

**Expected behavior**
As I understand it, the commission is displayed separately and only for the last month. But why??? Just do the same as on the website for the total amount.

**Screenshots**

**Phone (please complete the following information):**
 - OS: Doesn't matter
 - App Version: last

**Additional context**

**Comment by manuelsc** [comment]
Currently the app only displays the last month of execution rewards. We are currently working on bringing the full data to mobile in a future release.

**Comment by manuelsc** [comment]
This has been fixed in app version 4.5.0, it is now available on the App Store and Google Play Store.
