### ISSUE TITLE
Android notifications have HTML tags

### ISSUE THREAD

**Issue by celeduc** [gobitfly/eth2-beaconchain-explorer-app#256]
**Describe the bug**
Notifications on Android contain the `a` and/or `span` tags:

```
New Block Proposal
Validator <a href="https://beaconcha.in/validator/123456">123456</a> proposed block at slot <a href="https://beaconcha.in/slot/7654321"'>7654321</a> with
420.69 ETH execution reward.
```

**To Reproduce**
1. Follow something 
2. Wait for a notification 
3. See error

**Expected behavior**
should strip out markup, or render it.

**Screenshots**
![Screenshot_20231025-204822~2.png](https://github.com/gobitfly/eth2-beaconchain-explorer-app/assets/23334/0ac92854-5fba-45bf-8b3a-df32bae2f73b)

**Phone (please complete the following information):**
Pixel 6
Android 14, UP1A.231005.007
Beaconchain app v4.3.2

**Additional context**
Also happens for withdrawals and missed attestations, etc.

**Comment by manuelsc** [comment]
We have rolled out a fix for the ethereum mainnet notifications system. A fix for proposal notifications on testnet will follow early next week.
