### ISSUE TITLE
Sync Committee message not being populated with data

### ISSUE THREAD

**Issue by chrishobcroft** [gobitfly/eth2-beaconchain-explorer-app#257]
**Describe the bug**

Message notifying of an upcoming participation in a sync committee is not populating with data.

**To Reproduce**

1. Stake to a Validator
2. Wait to be selected for a sync committee
3. Tap on the "Soon: Sync Committee" notification 
4. See something like this, without data being populated regarding the timing of the sync committee opportunity:

![signal-2023-10-25-21-41-11-718](https://github.com/gobitfly/eth2-beaconchain-explorer-app/assets/2212651/cc7a137a-3a6e-46d2-bd87-3d9d2521ce59)

**Expected behavior**

I expect to see when the sync committee participation will start and end.

**Phone (please complete the following information):**
 - OS: Android 13
 - App Version: 4.3.2

**Comment by manuelsc** [comment]
Thank you for your bug report. We've fixed this issue on our end
