### ISSUE TITLE
Dashboard doesn't load

### ISSUE THREAD

**Issue by Xa52c** [gobitfly/eth2-beaconchain-explorer-app#263]
When I open the app the dashboard does not load, the loading icon just spins but data never loads. The other tabs work.

**Comment by manuelsc** [comment]
Please file a proper bug report using the github template. 
Do not provide logs here, instead follow this https://gist.github.com/Buttaa/ff0df0de5baf2501a35f743d92c6fbce and share your logs privately with the team either by opening a support ticket on our discord https://discord.com/invite/nVGbBnvvnA or mail manuel [at] bitfly.at
