### ISSUE TITLE
Can’t add new validators

### ISSUE THREAD

**Issue by locky192** [gobitfly/eth2-beaconchain-explorer-app#266]
**Describe the bug**
Unable to add new validators in app

**To Reproduce**
1. Go to validators tab
2. Click on search
3. type in a validator index/public key
4. Click search
5. Nothing happens

**Phone (please complete the following information):**
 - OS: iOS 17.2
 - App Version: 4.5.3

**Comment by crypto-scambaiter** [comment]
Same for me.
iOS 17.2.1
App version: 4.5.3

**Comment by manuelsc** [comment]
Fixed with App Version 4.5.4 in #267
