### ISSUE TITLE
Request: one tap to switch currency on the dashboard in iOS app

### ISSUE THREAD

**Issue by quangld** [gobitfly/eth2-beaconchain-explorer-app#5]
Switch currency on dashboard doesn't work on iOS app.
The Android app does allow to switch currency when tapping on the balance number on the dashboard.

So I'm not sure it's a bug or the iOS app has not been updated with this feature.

**Comment by manuelsc** [comment]
This feature is available on iOS. You probably need to select a "Display Currency" in your preferences first. Once set you can quickly toggle between ether and your selected fiat currency.

**Comment by quangld** [comment]
Thank! I didn't know that!
