### ISSUE TITLE
Premium doesn’t unlock after purchase

### ISSUE THREAD

**Issue by gdetari** [gobitfly/eth2-beaconchain-explorer-app#50]
I have purchased premium and the app still shows the option to upgrade premium, and I don’t have the benefits.

When I try to purchase again I get a popup Purchase “succesfull” (typo there) and to restart the app but even after restart is the same problem.

Seeing this on iOS14.8.1 and latest app version

**Comment by manuelsc** [comment]
In rare cases premium processing can take up to 40 minutes. You can wait or speed things up by logging out of the app and back into the same account. 
Let us know if this resolved your issue, we'll monitor this type of issues on our end and will find a better solution for how we handle the processing. Sorry for any inconvenience this may have caused and thank you for supporting us.

**Comment by gdetari** [comment]
Hey there, after 4 hours, it's still not processed. Logging in and out, deleting and reinstalling the app didn't help either.
If I tap restore purchase, I get "no purchase found on this account" yet the "Upgrade successfull" popup appears, prompting me to restart the app, which doesn't help either.

**Comment by manuelsc** [comment]
Has your order been processed by Apple? Can you mail me your purchase receipt from apples appstore? manuel@bitfly.at

**Comment by gdetari** [comment]
Sent mail.
