### ISSUE TITLE
Wrong yield for rocketpool validators 

### ISSUE THREAD

**Issue by torfbolt** [gobitfly/eth2-beaconchain-explorer-app#52]
**Describe the bug**
As a rocketpool node operator that also has solo staking validators, I would like to have the app calculate my staking rewards correctly. 

Basically for every solo validator / by default use the full reward, and for every rocketpool validator use the half reward + commission. 

**To Reproduce**
1. Open the app
2. Add a solo validator and a rocketpool validator that has 10% commission
3. Staking rewards are ~200% of the average validator reward.

**Expected behavior**
Expected rewards in this scenario are ~155% of the average validator reward.

**Comment by manuelsc** [comment]
Implemented in 3.1
