### ISSUE TITLE
eth2 deposit reference missing

### ISSUE THREAD

**Issue by judgewooden** [gobitfly/eth2-beaconchain-explorer-app#54]
**The bug**
Noticed that the eth2 deposit, with withdrawal credentials, is not always shown for active validators

**To Reproduce**
Two examples:
https://beaconcha.in/validator/94873#deposits (without eth2 deposit)
and
https://beaconcha.in/validator/8330#deposits (with eth2 deposit)

**Comment by guybrush** [comment]
Thank you, we fixed the issue.
