### ISSUE TITLE
Free users and Goldfish users cannot add more than 50 validators at once 

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer-app#57]
`0x701F4dcEAD1049FA01F321d49F6dca525cF4A5A5` has 66 validators but the app only recognizes 50 for free users. 
Works fine with Whale sub though.

![image](https://user-images.githubusercontent.com/26490734/147337136-c2e76cf3-8f50-489f-9c93-085bad1ba3ed.png)

**Comment by manuelsc** [comment]
Fixed, should work now on all app versions
