### ISSUE TITLE
iOS app fails to retrieve data

### ISSUE THREAD

**Issue by alextheseal** [gobitfly/eth2-beaconchain-explorer-app#69]
On many occasions, opening the app will show a spinning cursor with no data appearing. Closing the app and restarting will sometimes show the data immediately, however I’m now getting the app failing about 50% of the time. 

I have the same issue on both my iPhone and iPad, so issue is not related to one specific device

**Comment by manuelsc** [comment]
Please provide the app version and OS version

**Comment by alextheseal** [comment]
iOS version is 15.1.1 for iPhone, 15.2.1 for iPad. App version is 3.1.0 for both

**Comment by alextheseal** [comment]
Right now, iPhone is retrieving data, iPad has spinning cursor even after app restart ¯\_(ツ)_/¯

**Comment by manuelsc** [comment]
Hey, please update to 3.1.1. We had some issues on iOS with 1.3.0 which were fixed in 3.1.1 :)

**Comment by alextheseal** [comment]
Thanks, I’ve done that now. I thought that iOS would update all apps automatically, but obviously not.

**Comment by alextheseal** [comment]
I’ll check thoroughly over the next couple of days and let you know whether I see the issue again

**Comment by alextheseal** [comment]
The upgrade to 3.1.1 appears to have fixed the issue

**Comment by alextheseal** [comment]
Problem has reappeared, despite there being no new version. Both my iPhone and iPad fail to retrieve data, I just have a spinning cursor on a mostly black screen

**Comment by alextheseal** [comment]
Version is 3.1.1

**Comment by manuelsc** [comment]
How often does this happen? Does it happen after heavy app usage?
Are you using the machine monitoring feature and are you connected to the same wlan?

**Comment by alextheseal** [comment]
Hi Manuel,

It seems to be fine now, but I’m on the same LAN at the moment, iPhone using wifi, staking machine using a cable. I’ll let you know if I see the problem again, and will check whether it occurs when I am remote or on the same LAN.

And yes, I am using machine monitoring

Cheers

Andrew
