### ISSUE TITLE
Receiving eth client update available notifications for the wrong client.

### ISSUE THREAD

**Issue by jshufro** [gobitfly/eth2-beaconchain-explorer-app#72]
**Describe the bug**
I was on Prysm, but I want to be a [good eth citizen](https://www.youtube.com/watch?v=Wmo_XbLjVZs) so I switched to Nimbus.
In the Android app, I reconfigured my notifications to specify nimbus about a week ago:
![Screenshot_20220131-154836](https://user-images.githubusercontent.com/116244/151870831-7734adb9-c797-4f1e-98c2-1d2c289a9a9c.png)

Today, I received a notification about a Prysm update being available. 
![image](https://user-images.githubusercontent.com/116244/151871009-37da7c77-b62b-4ade-94b0-0e42e6d61acf.png)

**To Reproduce**
1. Set up eth client as Prysm and enable new version notifications
2. Switch eth client to Nimbus
3. Release a new Prysm version
4. Receive email notification for Prysm

**Expected behavior**
I would expect only to see Nimbus update available notifications

**Screenshots**
Above

**Phone (please complete the following information):**
 - OS: Android 12, Google Pixel 5
 - App Version 3.1.1

**Additional context**
invis sent me

**Comment by gsvpers** [comment]
Same here. Switched from teku to lighthouse, still getting teku notifications.

**Comment by jshufro** [comment]
I was able to resolve it be disabling and re-enabling notifications... still an annoying issue

**Comment by manuelsc** [comment]
Fixed in https://github.com/gobitfly/eth2-beaconchain-explorer-app/pull/101
