### ISSUE TITLE
[ request ] Periodic heartbeat push notification

### ISSUE THREAD

**Issue by actuallymentor** [gobitfly/eth2-beaconchain-explorer-app#75]
Hello team!

I'd love to be able to configure a periodic status notification, something along the lines of:

```
Title: Daily effectiveness report
Description: Your X validators have an effectiveness of Y and did Z proposals
```

One of the fears of a node operator is that something goes wrong and you miss it for too long. Personally I just had my phone reset and forgot to log into the beaconcha.in app for a few days. Nothing broke, but I would have loved to have noticed "hey my daily report didn't come thgouth".

Ideally this notification can be set to be daily/weekly/monthly. An MVP is a "Daily summary" toggle in the settings.

**Comment by Buttaa** [comment]
Hi @actuallymentor, we have a similar feature planned for Q2/3. 
I am going to close this issue; feel free to ping me if you have further ideas 🖖
