### ISSUE TITLE
hdd almost full over 26% alert

### ISSUE THREAD

**Issue by socal434** [gobitfly/eth2-beaconchain-explorer-app#76]
**Describe the bug**
hdd almost full at 26% alert that I can't disable, I can add another one from the app but not delete this one. There is also a machine offline that I can't delete but that doesn't cause any problems. 

**To Reproduce**
If notifications are on in the app, I start to randomly get hdd almost full alerts.

**Expected behavior**
I should be able to remove the 26% hdd alert either in the app or on the website so that I only have one alert that I set from the app.

**Screenshots**
These are the two alerts that I can't get rid of.
![image](https://user-images.githubusercontent.com/29628243/152835885-5aee2825-f7bc-445c-a84e-5af0cb5f109c.png)

This is after I went into the app and set an alert for hdd over 90% and machine offline. As you can see the 26% and the other machine offline are still there.
![Screenshot 2022-02-07 180456](https://user-images.githubusercontent.com/29628243/152836305-e151335a-3c2f-46b2-b6b6-8be14a08538e.jpg)

**Phone (please complete the following information):**
 - OS: Android 12
 - App Version 3.1.1

**Additional context**
n/a

**Comment by jaystyles** [comment]
Go
