### ISSUE TITLE
Alert if base_fee (gas price) is below X

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer-app#78]
Useful for RP node operators who want to start a new mini pool.

Thought: To avoid spam notifications, we should only notify once every 1hour and send another notification after 1 hour if gas price is still < x

**Comment by IngridMi** [comment]
> Useful for RP node operators who want to start a new mini pool.
> 
> Thought: To avoid spam notifications, we should only notify once every 1hour and send another notification after 1 hour if gas price is still < x

**Comment by manuelsc** [comment]
Might be to volatile for us to reliable offer as a notification service. Base fee adjusts every 13s, firebase notifications (our mobile push notification provider) are not instant due to battery constraints on the mobile device, so they may arrive minutes later.
