### ISSUE TITLE
APR is wrong when awaiting activation of additional validators

### ISSUE THREAD

**Issue by nomonkeynodeal** [gobitfly/eth2-beaconchain-explorer-app#8]
The APR is currently calculated from the total amount of ETH deposited in all validators. It should be calculated from the amount only in currently active validators.

![1622662549801](https://user-images.githubusercontent.com/84220428/120542439-ba2b6a80-c3b0-11eb-99ae-eeee6ebd3b23.jpg)

**Comment by manuelsc** [comment]
Thanks for the report. Fixed in 2.0.8
